<?xml version="1.0" encoding="UTF-8" ?>
<definitions name="EMA" targetNamespace="EMA"
	xmlns:tns="EMA"
	xmlns:xsd="http://www.w3.org/2001/XMLSchema"
	xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/"
	xmlns="http://schemas.xmlsoap.org/wsdl/">

	<types>
		<schema xmlns="http://www.w3.org/2001/XMLSchema">
		</schema>
	</types>

	<portType name="provisionaEMA">
		<operation name="activateEMA">
		</operation>
	</portType>

	<binding name="bindingEMASOAP" type="tns:provisionaEMA">
		<soap:binding transport="http://schemas.xmlsoap.org/soap/http"/>
		<operation name="activateEMA">
			<soap:operation soapAction="activateEMA"/>
		</operation>
	</binding>

	<service name="externalService">
		<port name="portEMASOAP" binding="tns:bindingEMASOAP">
			<soap:address location="http://localhost:8080/cwf/services/provisionaEMA"/>
		</port>
	</service>

</definitions>