update GG_RECIMSI set ESTADO='DISPONIBLE', ID_CLIENTE=null;
update GG_RECMSISDN set ESTADO='DISPONIBLE', ID_CLIENTE=null;
truncate TABLE GG_CLIENTECHARGINGSYSTEM ;
truncate TABLE GG_CLIENTEHLR;
truncate TABLE GG_CLIENTEBSCS;