--------------------------------------------------------
-- Archivo creado  - martes-marzo-07-2017   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table GG_CLIENTEHLR
--------------------------------------------------------

  CREATE TABLE "C##TRAIN2"."GG_CLIENTEHLR" 
   (	"IMSI" NUMBER(15,0), 
	"MSISDN" NUMBER(15,0), 
	"PROFILE" VARCHAR2(32 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
REM INSERTING into C##TRAIN2.GG_CLIENTEHLR
SET DEFINE OFF;
--------------------------------------------------------
--  DDL for Index PK_GG_CLIENTEHLR
--------------------------------------------------------

  CREATE UNIQUE INDEX "C##TRAIN2"."PK_GG_CLIENTEHLR" ON "C##TRAIN2"."GG_CLIENTEHLR" ("IMSI") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  Constraints for Table GG_CLIENTEHLR
--------------------------------------------------------

  ALTER TABLE "C##TRAIN2"."GG_CLIENTEHLR" ADD CONSTRAINT "PK_GG_CLIENTEHLR" PRIMARY KEY ("IMSI")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "C##TRAIN2"."GG_CLIENTEHLR" MODIFY ("IMSI" NOT NULL ENABLE);
