create or replace TYPE ACTINDEX_ARR AS VARRAY(1000) OF NUMBER(5);

create or replace TYPE AUDIT_NAMES_ARR AS VARRAY(100) OF VARCHAR2(128);

create or replace TYPE AUDIT_VALUES_ARR AS VARRAY(100) OF VARCHAR2(512);

create or replace TYPE CW_LANGUAGES_ARR AS VARRAY(100) OF VARCHAR2(5);

create or replace TYPE CW_TRANSLATIONIDS_ARR AS VARRAY(100) OF VARCHAR2(10);

create or replace TYPE CW_TRANSLATIONS_ARR AS VARRAY(100) OF NVARCHAR2(1024);

create or replace TYPE MSG_ID_ARR AS VARRAY(5000) OF NUMBER(16);

create or replace TYPE PROC_ID_ARR AS VARRAY(5000) OF NUMBER(16);
