DROP VIEW PR_BSCS_SERVICIO_VIGENTE ;

DROP TABLE PR_BSCS_CLIENTE CASCADE CONSTRAINTS ;

DROP TABLE PR_BSCS_CLIENTE_ESTADO CASCADE CONSTRAINTS ;

DROP TABLE PR_BSCS_MSISDN CASCADE CONSTRAINTS ;

DROP TABLE PR_BSCS_MSISDN_ESTADO CASCADE CONSTRAINTS ;

DROP TABLE PR_BSCS_PLAN CASCADE CONSTRAINTS ;

DROP TABLE PR_BSCS_SERVICIO CASCADE CONSTRAINTS ;

DROP TABLE PR_BSCS_SERVICIO_ESTADO CASCADE CONSTRAINTS ;

CREATE TABLE PR_BSCS_CLIENTE
  (
    SYSTEM_ID_CLIENTE_N_BSCS NUMBER (10) NOT NULL ,
    SYSTEM_ID_CLIENTE_C_BSCS VARCHAR2 (10) ,
    FECHA_CREACION           DATE ,
    ID_CLIENTE_ESTADO        VARCHAR2 (1) NOT NULL ,
    RUT                      VARCHAR2 (15)
  ) ;
ALTER TABLE PR_BSCS_CLIENTE ADD CONSTRAINT PR_CLIENTE_PK PRIMARY KEY ( SYSTEM_ID_CLIENTE_N_BSCS ) ;


CREATE TABLE PR_BSCS_CLIENTE_ESTADO
  (
    ID_CLIENTE_ESTADO   VARCHAR2 (1) NOT NULL ,
    DESC_CLIENTE_ESTADO VARCHAR2 (30)
  ) ;
ALTER TABLE PR_BSCS_CLIENTE_ESTADO ADD CONSTRAINT BSORS_CLIENTE_ESTADO_PK PRIMARY KEY ( ID_CLIENTE_ESTADO ) ;


CREATE TABLE PR_BSCS_MSISDN
  (
    MSISDN           VARCHAR2 (15) NOT NULL ,
    ID_MSISDN_ESTADO VARCHAR2 (1) NOT NULL
  ) ;
ALTER TABLE PR_BSCS_MSISDN ADD CONSTRAINT PR_BSCS_MSISDN_PK PRIMARY KEY ( MSISDN ) ;


CREATE TABLE PR_BSCS_MSISDN_ESTADO
  (
    ID_MSISDN_ESTADO   VARCHAR2 (1) NOT NULL ,
    DESC_MSISDN_ESTADO VARCHAR2 (30)
  ) ;
ALTER TABLE PR_BSCS_MSISDN_ESTADO ADD CONSTRAINT PR_BSCS_MSISDN_ESTADO_PK PRIMARY KEY ( ID_MSISDN_ESTADO ) ;


CREATE TABLE PR_BSCS_PLAN
  (
    SYSTEM_ID_PLAN_N_BSCS NUMBER (10) NOT NULL ,
    SYSTEM_ID_PLAN_C_BSCS VARCHAR2 (10) ,
    DESC_PLAN_BSCS        VARCHAR2 (30)
  ) ;
ALTER TABLE PR_BSCS_PLAN ADD CONSTRAINT PR_BSCS_PLAN_PK PRIMARY KEY ( SYSTEM_ID_PLAN_N_BSCS ) ;


CREATE TABLE PR_BSCS_SERVICIO
  (
    SYSTEM_ID_SERVICIO_N_BSCS NUMBER (10) ,
    SYSTEM_ID_SERVICIO_C_BSCS VARCHAR2 (10) ,
    SYSTEM_ID_CLIENTE_N_BSCS  NUMBER (10) ,
    SYSTEM_ID_CLIENTE_C_BSCS  VARCHAR2 (10) ,
    MSISDN                    VARCHAR2 (15) NOT NULL ,
    SYSTEM_ID_PLAN_N_BSCS     NUMBER (10) ,
    SYSTEM_ID_PLAN_C_BSCS     VARCHAR2 (10) ,
    ORDER_ID                  VARCHAR2 (16) ,
    ID_SERVICIO_ESTADO        VARCHAR2 (1) NOT NULL ,
    FECHA_ACTIVACION          DATE ,
    FECHA_ACTUALIZACION       DATE
  ) ;


CREATE TABLE PR_BSCS_SERVICIO_ESTADO
  (
    ID_SERVICIO_ESTADO   VARCHAR2 (1) NOT NULL ,
    DESC_SERVICIO_ESTADO VARCHAR2 (30)
  ) ;
ALTER TABLE PR_BSCS_SERVICIO_ESTADO ADD CONSTRAINT PR_BSCS_SERVICIO_ESTADO_PK PRIMARY KEY ( ID_SERVICIO_ESTADO ) ;


ALTER TABLE PR_BSCS_MSISDN ADD CONSTRAINT PR_BSCS_MSISDN_ESTADO_FK FOREIGN KEY ( ID_MSISDN_ESTADO ) REFERENCES PR_BSCS_MSISDN_ESTADO ( ID_MSISDN_ESTADO ) ON
DELETE CASCADE ;

ALTER TABLE PR_BSCS_SERVICIO ADD CONSTRAINT PR_BSCS_SERIO_BSCS_CLIENTE_FK FOREIGN KEY ( MSISDN ) REFERENCES PR_BSCS_MSISDN ( MSISDN ) ;

ALTER TABLE PR_BSCS_SERVICIO ADD CONSTRAINT PR_BSCS_SERVICIO_ESTADO_FK FOREIGN KEY ( ID_SERVICIO_ESTADO ) REFERENCES PR_BSCS_SERVICIO_ESTADO ( ID_SERVICIO_ESTADO ) ;

ALTER TABLE PR_BSCS_CLIENTE ADD CONSTRAINT PR_ID_CLIENTE_ESTADO FOREIGN KEY ( ID_CLIENTE_ESTADO ) REFERENCES PR_BSCS_CLIENTE_ESTADO ( ID_CLIENTE_ESTADO ) ;

CREATE OR REPLACE VIEW PR_BSCS_SERVICIO_VIGENTE  AS
SELECT c.SYSTEM_ID_SERVICIO_N_BSCS,
  c.SYSTEM_ID_SERVICIO_C_BSCS,
  c.SYSTEM_ID_CLIENTE_N_BSCS,
  c.SYSTEM_ID_CLIENTE_C_BSCS,
  c.MSISDN,
  c.SYSTEM_ID_PLAN_N_BSCS,
  c.SYSTEM_ID_PLAN_C_BSCS,
  c.ORDER_ID,
  c.ID_SERVICIO_ESTADO,
  c.FECHA_ACTIVACION,
  c.FECHA_ACTUALIZACION
FROM
  (SELECT a.MSISDN,
    MAX(a.FECHA_ACTUALIZACION) FECHA_ACTUALIZACION
  FROM PR_BSCS_SERVICIO a
  GROUP BY a.MSISDN
  ) b,
  PR_BSCS_SERVICIO c
WHERE b.MSISDN            = c.MSISDN
AND b.FECHA_ACTUALIZACION = c.FECHA_ACTUALIZACION ;

DROP SEQUENCE SEQ_ID_CLIENTE_BSCS;
DROP SEQUENCE SEQ_ID_PLAN_BSCS;
DROP SEQUENCE SEQ_ID_SERVICIO_BSCS;

CREATE SEQUENCE SEQ_ID_CLIENTE_BSCS 	MINVALUE 	1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 100 CACHE 20 NOORDER  NOCYCLE  NOPARTITION ;
CREATE SEQUENCE SEQ_ID_PLAN_BSCS 		MINVALUE 		1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 100 CACHE 20 NOORDER  NOCYCLE  NOPARTITION ;
CREATE SEQUENCE SEQ_ID_SERVICIO_BSCS 	MINVALUE 	1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 100 CACHE 20 NOORDER  NOCYCLE  NOPARTITION ;

insert into PR_BSCS_CLIENTE_ESTADO values ('1','ACTIVO');
insert into PR_BSCS_CLIENTE_ESTADO values ('2','DESACTIVO');

insert into PR_BSCS_MSISDN_ESTADO values ('1','DISPONIBLE');
insert into PR_BSCS_MSISDN_ESTADO values ('2','RESERVADO');
insert into PR_BSCS_MSISDN_ESTADO values ('3','ASIGNADO');

insert into PR_BSCS_SERVICIO_ESTADO values ('1','ACTIVO');
insert into PR_BSCS_SERVICIO_ESTADO values ('2','SUSPENDIDO');
insert into PR_BSCS_SERVICIO_ESTADO values ('3','DESACTIVADO');

insert into PR_BSCS_PLAN values(1,'1', 'Plan Anita');
insert into PR_BSCS_PLAN values(2,'2', 'Plan Carlitos');
insert into PR_BSCS_PLAN values(3,'3', 'Plan Global');
insert into PR_BSCS_PLAN values(4,'A', 'Plan CC');

insert into PR_BSCS_MSISDN values('56992270351', 1);
insert into PR_BSCS_MSISDN values('56992270352', 1);
insert into PR_BSCS_MSISDN values('56992270353', 1);
insert into PR_BSCS_MSISDN values('56992270354', 1);
insert into PR_BSCS_MSISDN values('56992270355', 1);
insert into PR_BSCS_MSISDN values('56992270356', 1);
insert into PR_BSCS_MSISDN values('56992270357', 1);
insert into PR_BSCS_MSISDN values('56992270358', 1);
insert into PR_BSCS_MSISDN values('56992270359', 1);
COMMIT;


