DROP VIEW PR_CS_SERVICIO_VIGENTE ;

DROP TABLE PR_CS_PLAN CASCADE CONSTRAINTS ;

DROP TABLE PR_CS_SALDOS CASCADE CONSTRAINTS ;

DROP TABLE PR_CS_SERVICIO CASCADE CONSTRAINTS ;

DROP TABLE PR_CS_SERVICIO_ESTADO CASCADE CONSTRAINTS ;

CREATE TABLE PR_CS_PLAN
  (
    SYSTEM_ID_PLAN_N_CS NUMBER (10) NOT NULL ,
    SYSTEM_ID_PLAN_C_CS VARCHAR2 (10) ,
    DESC_PLAN           VARCHAR2 (30) ,
    SALDO_INICIAL       NUMBER (10)
  ) ;
ALTER TABLE PR_CS_PLAN ADD CONSTRAINT PR_PLAN_PK PRIMARY KEY ( SYSTEM_ID_PLAN_N_CS ) ;


CREATE TABLE PR_CS_SALDOS
  (
    SYSTEM_ID_SERVICIO_N_CS NUMBER (10) NOT NULL ,
    SALDO_INICIAL           NUMBER (10) ,
    SALDO_ACTUAL            NUMBER (10) ,
    FECHA_ULTIMO_SALDO      DATE
  ) ;
ALTER TABLE PR_CS_SALDOS ADD CONSTRAINT PR_SALDOS_PK PRIMARY KEY ( SYSTEM_ID_SERVICIO_N_CS ) ;


CREATE TABLE PR_CS_SERVICIO
  (
    SYSTEM_ID_SERVICIO_N_CS NUMBER (10) NOT NULL ,
    SYSTEM_ID_SERVICIO_C_CS VARCHAR2 (10) ,
    MSISDN                  VARCHAR2 (15) ,
    SYSTEM_ID_PLAN_C_CS     VARCHAR2 (10) NOT NULL ,
    ORDER_ID                VARCHAR2 (16) ,
    ID_SERVICIO_ESTADO      VARCHAR2 (1) NOT NULL ,
    FECHA_ACTIVACION        DATE ,
    FECHA_ACTUALIZACION     DATE
  ) ;


CREATE TABLE PR_CS_SERVICIO_ESTADO
  (
    ID_SERVICIO_ESTADO VARCHAR2 (1) NOT NULL ,
    DESC_ESTADO        VARCHAR2 (30)
  ) ;
ALTER TABLE PR_CS_SERVICIO_ESTADO ADD CONSTRAINT PR_SERVICIO_ESTADO_PK PRIMARY KEY ( ID_SERVICIO_ESTADO ) ;

ALTER TABLE PR_CS_SERVICIO ADD CONSTRAINT PR_SERVICIO_CS_ESTADO_FK FOREIGN KEY ( ID_SERVICIO_ESTADO ) REFERENCES PR_CS_SERVICIO_ESTADO ( ID_SERVICIO_ESTADO ) ;

CREATE OR REPLACE VIEW PR_CS_SERVICIO_VIGENTE  AS
SELECT c.SYSTEM_ID_SERVICIO_N_CS,
  c.SYSTEM_ID_SERVICIO_C_CS,
  c.MSISDN,
  c.SYSTEM_ID_PLAN_C_CS,
  c.ORDER_ID,
  c.ID_SERVICIO_ESTADO,
  c.FECHA_ACTIVACION,
  c.FECHA_ACTUALIZACION
FROM
  (SELECT a.MSISDN,
    MAX(a.FECHA_ACTUALIZACION) FECHA_ACTUALIZACION
  FROM PR_CS_SERVICIO a
  GROUP BY a.MSISDN
  ) b,
  PR_CS_SERVICIO c
WHERE b.MSISDN            = c.MSISDN
AND b.FECHA_ACTUALIZACION = c.FECHA_ACTUALIZACION 
;


CREATE OR REPLACE SEQUENCE SEQ_ID_SERVICIO_CS MINVALUE 	1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 100 CACHE 20 NOORDER  NOCYCLE  NOPARTITION ;


insert into PR_cs_servicio_estado values ('1','ACTIVO');
insert into PR_cs_servicio_estado values ('2','SUSPENDIDO');
insert into PR_cs_servicio_estado values ('3','DESACTIVADO');

insert into PR_CS_PLAN values(1,'1', 'Plan Anita', 5000);
insert into PR_CS_PLAN values(2,'2', 'Plan Carlitos', 10000);
insert into PR_CS_PLAN values(3,'3', 'Plan Global', 15000);

COMMIT;