
DROP TABLE EMA_ESTADO_SERVICIO CASCADE CONSTRAINTS ;

DROP TABLE EMA_NODO CASCADE CONSTRAINTS ;

DROP TABLE EMA_PROFILE CASCADE CONSTRAINTS ;

DROP TABLE EMA_PROFILE_DETALLE CASCADE CONSTRAINTS ;

DROP TABLE EMA_SERVICIO CASCADE CONSTRAINTS ;

DROP TABLE EMA_SERVICIO_NODO_ACTIVO CASCADE CONSTRAINTS ;

CREATE TABLE EMA_ESTADO_SERVICIO
  (
    ID_ESTADO   VARCHAR2 (1) NOT NULL ,
    DESC_ESTADO VARCHAR2 (30)
  ) ;
ALTER TABLE EMA_ESTADO_SERVICIO ADD CONSTRAINT EMA_ESTADO_SERVICIO_PK PRIMARY KEY ( ID_ESTADO ) ;


CREATE TABLE EMA_NODO
  (
    ID_NODO    NUMBER (5) NOT NULL ,
    DESC_NODO  VARCHAR2 (30) ,
    PLATAFORMA VARCHAR2 (30)
  ) ;
ALTER TABLE EMA_NODO ADD CONSTRAINT EMA_NODO_PK PRIMARY KEY ( ID_NODO ) ;


CREATE TABLE EMA_PROFILE
  (
    ID_PROFILE   NUMBER (5) NOT NULL ,
    DESC_PROFILE VARCHAR2 (30)
  ) ;
ALTER TABLE EMA_PROFILE ADD CONSTRAINT EMA_PROFILE_PK PRIMARY KEY ( ID_PROFILE ) ;


CREATE TABLE EMA_PROFILE_DETALLE
  (
    ID_NODO              NUMBER (5) NOT NULL ,
    ID_PROFILE           NUMBER (5) NOT NULL ,
    DESC_PROFILE_DETALLE VARCHAR2 (30)
  ) ;


CREATE TABLE EMA_SERVICIO
  (
    MSISDN           VARCHAR2 (15) NOT NULL ,
    ID_PROFILE       NUMBER (5) NOT NULL ,
    ID_ESTADO        VARCHAR2 (1) NOT NULL ,
    FECHA_ACTIVACION DATE ,
    ORDER_ID         VARCHAR2 (16)
  ) ;
ALTER TABLE EMA_SERVICIO ADD CONSTRAINT EMA_SERVICIO_PK PRIMARY KEY ( MSISDN, ID_PROFILE, ID_ESTADO ) ;


CREATE TABLE EMA_SERVICIO_NODO_ACTIVO
  (
    ID_NODO          NUMBER (5) NOT NULL ,
    MSISDN           VARCHAR2 (15) NOT NULL ,
    FECHA_ACTIVACION DATE
  ) ;
ALTER TABLE EMA_SERVICIO_NODO_ACTIVO ADD CONSTRAINT EMA_SERVICIO_NODO_ACTIVO_PK PRIMARY KEY ( ID_NODO, MSISDN ) ;


ALTER TABLE EMA_SERVICIO_NODO_ACTIVO ADD CONSTRAINT EMA_ACTIVO_EMA_FK FOREIGN KEY ( ID_NODO ) REFERENCES EMA_NODO ( ID_NODO ) ;

ALTER TABLE EMA_PROFILE_DETALLE ADD CONSTRAINT EMA_PROFILE_DETALLE_FK FOREIGN KEY ( ID_PROFILE ) REFERENCES EMA_PROFILE ( ID_PROFILE ) ;

ALTER TABLE EMA_PROFILE_DETALLE ADD CONSTRAINT EMA_PROFILE_NODO_FK FOREIGN KEY ( ID_NODO ) REFERENCES EMA_NODO ( ID_NODO ) ;

ALTER TABLE EMA_SERVICIO ADD CONSTRAINT EMA_SERVICIO_FK FOREIGN KEY ( ID_ESTADO ) REFERENCES EMA_ESTADO_SERVICIO ( ID_ESTADO ) ;

ALTER TABLE EMA_SERVICIO ADD CONSTRAINT EMA_SERVICIO_PROFILE_FK FOREIGN KEY ( ID_PROFILE ) REFERENCES EMA_PROFILE ( ID_PROFILE ) ;

insert into EMA_ESTADO_SERVICIO values ('1','ACTIVO');
insert into EMA_ESTADO_SERVICIO values ('2','SUSPENDIDO');
insert into EMA_ESTADO_SERVICIO values ('3','DESACTIVADO');
COMMIT;

insert into EMA_NODO values ('1','PLATAFORMA DE VOZ','VOZ');
insert into EMA_NODO values ('2','PLATAFORMA DE SMS','SMS');
insert into EMA_NODO values ('3','PLATAFORMA DE DATOS','DATOS');
COMMIT;

insert into EMA_PROFILE values ('1','PERFIL VOZ');
insert into EMA_PROFILE values ('2','PERFIL VOZ + SMS');
COMMIT;

insert into EMA_PROFILE_DETALLE values ('1','1','VOZ');
insert into EMA_PROFILE_DETALLE values ('1','2','SMS');
insert into EMA_PROFILE_DETALLE values ('2','2','SMS');


COMMIT;