DROP VIEW PR_EMA_SERVICIO_VIGENTE;

DROP VIEW PR_EMA_PROFILE_NODO;

DROP VIEW PR_EMA_SERVICIO_NODO_DETALLE;

DROP TABLE PR_EMA_ESTADO_SERVICIO CASCADE CONSTRAINTS ;

DROP TABLE PR_EMA_NODO CASCADE CONSTRAINTS ;

DROP TABLE PR_EMA_PROFILE CASCADE CONSTRAINTS ;

DROP TABLE PR_EMA_PROFILE_DETALLE CASCADE CONSTRAINTS ;

DROP TABLE PR_EMA_SERVICIO CASCADE CONSTRAINTS ;

DROP TABLE PR_EMA_SERVICIO_NODO_ACTIVO CASCADE CONSTRAINTS ;

CREATE TABLE PR_EMA_ESTADO_SERVICIO
  (
    ID_ESTADO   VARCHAR2 (1) NOT NULL ,
    DESC_ESTADO VARCHAR2 (30)
  ) ;
ALTER TABLE PR_EMA_ESTADO_SERVICIO ADD CONSTRAINT EMA_ESTADO_SERVICIO_PK PRIMARY KEY ( ID_ESTADO ) ;


CREATE TABLE PR_EMA_NODO
  (
    SYSTEM_ID_NODO_N_EMA NUMBER (10) NOT NULL ,
    SYSTEM_ID_NODO_C_EMA VARCHAR2 (10) ,
    DESC_NODO            VARCHAR2 (30) ,
    PLATAFORMA           VARCHAR2 (30)
  ) ;
ALTER TABLE PR_EMA_NODO ADD CONSTRAINT EMA_NODO_PK PRIMARY KEY ( SYSTEM_ID_NODO_N_EMA ) ;


CREATE TABLE PR_EMA_PROFILE
  (
    SYSTEM_ID_PROFILE_N_EMA NUMBER (10) NOT NULL ,
    SYSTEM_ID_PROFILE_C_EMA VARCHAR2 (10) ,
    DESC_PROFILE            VARCHAR2 (30)
  ) ;
ALTER TABLE PR_EMA_PROFILE ADD CONSTRAINT EMA_PROFILE_PK PRIMARY KEY ( SYSTEM_ID_PROFILE_N_EMA ) ;


CREATE TABLE PR_EMA_PROFILE_DETALLE
  (
    SYSTEM_ID_PROFILE_N_EMA NUMBER (10) NOT NULL ,
    SYSTEM_ID_PROFILE_C_EMA VARCHAR2 (10) ,
    SYSTEM_ID_NODO_N_EMA    NUMBER (10) NOT NULL ,
    SYSTEM_ID_NODO_C_EMA    VARCHAR2 (10) ,
    DESC_PROFILE_DETALLE    VARCHAR2 (30)
  ) ;


CREATE TABLE PR_EMA_SERVICIO
  (
    SYSTEM_ID_SERVICIO_N_EMA NUMBER (10) ,
    SYSTEM_ID_SERVICIO_C_EMA VARCHAR2 (10) ,
    MSISDN                   VARCHAR2 (15) NOT NULL ,
    SYSTEM_ID_PROFILE_N_EMA  NUMBER (10) ,
    SYSTEM_ID_PROFILE_C_EMA  VARCHAR2 (10) ,
    ORDER_ID                 VARCHAR2 (16) ,
    ID_ESTADO                VARCHAR2 (1) NOT NULL ,
    FECHA_ACTIVACION         DATE ,
    FECHA_ACTUALIZACION      DATE
  ) ;


CREATE TABLE PR_EMA_SERVICIO_NODO_ACTIVO
  (
    SYSTEM_ID_NODO_N_EMA NUMBER (10) NOT NULL ,
    SYSTEM_ID_NODO_C_EMA VARCHAR2 (10) NOT NULL ,
    MSISDN               VARCHAR2 (15) NOT NULL ,
    FECHA_ACTIVACION     DATE
  ) ;

ALTER TABLE PR_EMA_PROFILE_DETALLE ADD CONSTRAINT EMA_PROFILE_DETALLE_FK FOREIGN KEY ( SYSTEM_ID_PROFILE_N_EMA ) REFERENCES PR_EMA_PROFILE ( SYSTEM_ID_PROFILE_N_EMA ) ;

ALTER TABLE PR_EMA_PROFILE_DETALLE ADD CONSTRAINT EMA_PROFILE_NODO_FK FOREIGN KEY ( SYSTEM_ID_NODO_N_EMA ) REFERENCES PR_EMA_NODO ( SYSTEM_ID_NODO_N_EMA ) ;

ALTER TABLE PR_EMA_SERVICIO ADD CONSTRAINT EMA_SERVICIO_FK FOREIGN KEY ( ID_ESTADO ) REFERENCES PR_EMA_ESTADO_SERVICIO ( ID_ESTADO ) ;


CREATE OR REPLACE VIEW PR_EMA_SERVICIO_VIGENTE
AS
  SELECT c.SYSTEM_ID_SERVICIO_N_EMA,
    c.SYSTEM_ID_SERVICIO_C_EMA,
    c.MSISDN,
    c.SYSTEM_ID_PROFILE_N_EMA,
    c.SYSTEM_ID_PROFILE_C_EMA,
    c.ORDER_ID,
    c.ID_ESTADO,
    c.FECHA_ACTIVACION,
    c.FECHA_ACTUALIZACION
  FROM
    (SELECT a.MSISDN,
      MAX(a.FECHA_ACTUALIZACION) FECHA_ACTUALIZACION
    FROM PR_EMA_SERVICIO a
    GROUP BY a.MSISDN
    ) b,
    PR_EMA_SERVICIO c
  WHERE b.MSISDN            = c.MSISDN
  AND b.FECHA_ACTUALIZACION = c.FECHA_ACTUALIZACION ;

  
  CREATE OR REPLACE view PR_EMA_PROFILE_NODO as
select 
  a.SYSTEM_ID_PROFILE_N_EMA SYSTEM_ID_PROFILE_N_EMA,
  a.SYSTEM_ID_PROFILE_C_EMA SYSTEM_ID_PROFILE_C_EMA,
  a.DESC_PROFILE DESC_PROFILE,
  b.DESC_NODO DESC_NODO,
  b.PLATAFORMA PLATAFORMA,
  C.DESC_PROFILE_DETALLE DESC_PROFILE_DETALLE
from 
  PR_EMA_PROFILE a,
  PR_EMA_NODO b,
  PR_EMA_PROFILE_DETALLE c
  where a.SYSTEM_ID_PROFILE_N_EMA=c.SYSTEM_ID_PROFILE_N_EMA and
  c.SYSTEM_ID_NODO_N_EMA=b.SYSTEM_ID_NODO_N_EMA;
  
  CREATE OR REPLACE view PR_EMA_SERVICIO_NODO_DETALLE as
  select 
  a.SYSTEM_ID_NODO_N_EMA,
  a.DESC_NODO DESC_NONO,
  b.MSISDN MSISDN,
  b.FECHA_ACTIVACION FECHA_ACTIVACION
  from PR_EMA_NODO a, PR_EMA_SERVICIO_NODO_ACTIVO b
  where a.SYSTEM_ID_NODO_N_EMA=b.SYSTEM_ID_NODO_N_EMA;

  
CREATE OR REPLACE VIEW PR_EMA_NODO_CONFIGURADO as 
SELECT 	C.system_id_nodo_n_ema system_id_nodo_n_ema,
		C.system_id_nodo_c_ema system_id_nodo_c_ema,
		C.system_id_profile_n_ema system_id_profile_n_ema,
		C.system_id_profile_c_ema system_id_profile_c_ema,
		D.DESC_PROFILE_DETALLE DESC_PROFILE_DETALLE,
		cast(nvl(length(substr(D.DESC_PROFILE_DETALLE,1,1)),0) as number(1)) CONFIGURADO,
		C.PLATAFORMA
from 	(  	select  a.system_id_nodo_n_ema system_id_nodo_n_ema, 
					a.system_id_nodo_c_ema system_id_nodo_c_ema, 
					b.system_id_profile_n_ema system_id_profile_n_ema,
					b.system_id_profile_c_ema system_id_profile_c_ema,
					a.plataforma
			from    pr_ema_nodo a ,
					pr_ema_profile b
		) 	c,
		pr_ema_profile_detalle D
where C.system_id_nodo_n_ema=D.system_id_nodo_n_ema(+) and
      C.system_id_profile_n_ema=D.system_id_profile_n_ema(+);



  
  --SECUENCIAS

  
DROP SEQUENCE SEQ_ID_NODO_EMA;

DROP SEQUENCE SEQ_ID_SERVICIO_EMA;

DROP SEQUENCE SEQ_ID_PERFIL_EMA;

CREATE SEQUENCE SEQ_ID_NODO_EMA     INCREMENT BY 1 START WITH 100;

CREATE SEQUENCE SEQ_ID_SERVICIO_EMA INCREMENT BY 1 START WITH 100;

CREATE SEQUENCE SEQ_ID_PERFIL_EMA     INCREMENT BY 1 START WITH 100;

--------------------------------------------------------------------------------------------------------

insert into PR_EMA_ESTADO_SERVICIO values ('1','ACTIVO');
insert into PR_EMA_ESTADO_SERVICIO values ('2','SUSPENDIDO');
insert into PR_EMA_ESTADO_SERVICIO values ('3','DESACTIVADO');

insert into PR_EMA_NODO values (1,'1','PLATAFORMA DE VOZ','VOZ');
insert into PR_EMA_NODO values (2,'2','PLATAFORMA DE SMS','SMS');
insert into PR_EMA_NODO values (3,'3','PLATAFORMA DE DATOS','DATOS');

insert into PR_EMA_PROFILE values (1,'1','PERFIL VOZ');
insert into PR_EMA_PROFILE values (2,'2','PERFIL VOZ + SMS');

insert into PR_EMA_PROFILE_DETALLE values (1,'1',1,'1','VOZ');
insert into PR_EMA_PROFILE_DETALLE values (2,'2',1,'1','VOZ');
insert into PR_EMA_PROFILE_DETALLE values (2,'2',2,'2','SMS');

COMMIT;

--------------------------------------------------------------------------------------------------------
