
Insert into C##TRAIN.OM_PARAMETROS_NODOS (ID,POID,IDNODO,IDPARAMETRO,VALOR) values ('1','CARLITOS','BSCS','ID_PLAN_BSCS','PLAN_BSCS');
Insert into C##TRAIN.OM_PARAMETROS_NODOS (ID,POID,IDNODO,IDPARAMETRO,VALOR) values ('2','CARLITOS','CS','ID_PLAN_CS','PLAN_CS');
Insert into C##TRAIN.OM_PARAMETROS_NODOS (ID,POID,IDNODO,IDPARAMETRO,VALOR) values ('3','CARLITOS','EMA','PROFILE','PROFILE_EMA');
commit;

