
Insert into C##TRAIN.OM_PARAMETROS_NODOS (ID,POID,IDNODO,IDPARAMETRO,VALOR) values ('1','PO_BASICA_PREPAGO','BSCS','ID_PLAN_BSCS','1');
Insert into C##TRAIN.OM_PARAMETROS_NODOS (ID,POID,IDNODO,IDPARAMETRO,VALOR) values ('2','PO_BASICA_PREPAGO','CS','ID_PLAN_CS','1');
Insert into C##TRAIN.OM_PARAMETROS_NODOS (ID,POID,IDNODO,IDPARAMETRO,VALOR) values ('3','PO_BASICA_PREPAGO','EMA','PROFILE','1');

INSERT INTO OE_CLIENTE(RUT, NOMBRE, DIRECCION, COMUNA, CIUDAD)
VALUES('13668652-6', 'Luis Gonzalez Donoso', 'Camino de las Amapolas 5525', 'Peñalolen', 'Santiago');
commit;

