CREATE TABLE BSCS_CLIENTE
  (
    ID_CLIENTE_BSCS   NUMBER (5) NOT NULL ,
    FECHA_CREACION    DATE ,
    ID_CLIENTE_ESTADO VARCHAR2 (1) NOT NULL ,
    RUT               VARCHAR2 (15)
  )
  NOLOGGING ;
ALTER TABLE BSCS_CLIENTE ADD CONSTRAINT BSCS_CLIENTE_PK PRIMARY KEY ( ID_CLIENTE_BSCS ) ;


CREATE TABLE BSCS_CLIENTE_ESTADO
  (
    ID_CLIENTE_ESTADO   VARCHAR2 (1) NOT NULL ,
    DESC_CLIENTE_ESTADO VARCHAR2 (30)
  )
  NOLOGGING ;
ALTER TABLE BSCS_CLIENTE_ESTADO ADD CONSTRAINT BSCS_CLIENTE_ESTADO_PK PRIMARY KEY ( ID_CLIENTE_ESTADO ) ;


CREATE TABLE BSCS_MSISDN
  (
    MSISDN           VARCHAR2 (10) NOT NULL ,
    ID_MSISDN_ESTADO VARCHAR2 (1) NOT NULL
  )
  NOLOGGING ;
ALTER TABLE BSCS_MSISDN ADD CONSTRAINT BSCS_MSISDN_PK PRIMARY KEY ( MSISDN ) ;


CREATE TABLE BSCS_MSISDN_ESTADO
  (
    ID_MSISDN_ESTADO   VARCHAR2 (1) NOT NULL ,
    DESC_MSISDN_ESTADO VARCHAR2 (30)
  )
  NOLOGGING ;
ALTER TABLE BSCS_MSISDN_ESTADO ADD CONSTRAINT BSCS_MSISDN_ESTADO_PK PRIMARY KEY ( ID_MSISDN_ESTADO ) ;


CREATE TABLE BSCS_PLAN
  (
    ID_PLAN_BSCS   NUMBER (5) NOT NULL ,
    DESC_PLAN_BSCS VARCHAR2 (30)
  )
  NOLOGGING ;
ALTER TABLE BSCS_PLAN ADD CONSTRAINT BSCS_PLAN_PK PRIMARY KEY ( ID_PLAN_BSCS ) ;


CREATE TABLE BSCS_SERVICIO
  (
    ID_CLIENTE_BSCS    NUMBER (5) NOT NULL ,
    MSISDN             VARCHAR2 (10) NOT NULL ,
    FECHA_ACTIVACION   DATE ,
    ID_SERVICIO_ESTADO VARCHAR2 (1) NOT NULL ,
    ID_PLAN_BSCS       NUMBER (5) NOT NULL
  )
  NOLOGGING ;


CREATE TABLE BSCS_SERVICIO_ESTADO
  (
    ID_SERVICIO_ESTADO   VARCHAR2 (1) NOT NULL ,
    DESC_SERVICIO_ESTADO VARCHAR2 (30)
  )
  NOLOGGING ;
ALTER TABLE BSCS_SERVICIO_ESTADO ADD CONSTRAINT BSCS_SERVICIO_ESTADO_PK PRIMARY KEY ( ID_SERVICIO_ESTADO ) ;


--  ERROR: FK name length exceeds maximum allowed length(30)
ALTER TABLE BSCS_MSISDN ADD CONSTRAINT BSCS_MSISDN_ESTADO_FK FOREIGN KEY ( ID_MSISDN_ESTADO ) REFERENCES BSCS_MSISDN_ESTADO ( ID_MSISDN_ESTADO ) ON
DELETE CASCADE NOT DEFERRABLE ;

ALTER TABLE BSCS_SERVICIO ADD CONSTRAINT BSCS_SERVICIO_BSCS_CLIENTE_FK FOREIGN KEY ( ID_CLIENTE_BSCS ) REFERENCES BSCS_CLIENTE ( ID_CLIENTE_BSCS ) ON
DELETE CASCADE NOT DEFERRABLE ;

ALTER TABLE BSCS_SERVICIO ADD CONSTRAINT BSCS_SERVICIO_BSCS_MSISDN_FK FOREIGN KEY ( MSISDN ) REFERENCES BSCS_MSISDN ( MSISDN ) NOT DEFERRABLE ;

ALTER TABLE BSCS_SERVICIO ADD CONSTRAINT BSCS_SERVICIO_BSCS_PLAN_FK FOREIGN KEY ( ID_PLAN_BSCS ) REFERENCES BSCS_PLAN ( ID_PLAN_BSCS ) NOT DEFERRABLE ;

--  ERROR: FK name length exceeds maximum allowed length(30)
ALTER TABLE BSCS_SERVICIO ADD CONSTRAINT BSCS_SERVICIO_ESTADO_FK FOREIGN KEY ( ID_SERVICIO_ESTADO ) REFERENCES BSCS_SERVICIO_ESTADO ( ID_SERVICIO_ESTADO ) NOT DEFERRABLE ;

ALTER TABLE BSCS_CLIENTE ADD CONSTRAINT ID_CLIENTE_ESTADO FOREIGN KEY ( ID_CLIENTE_ESTADO ) REFERENCES BSCS_CLIENTE_ESTADO ( ID_CLIENTE_ESTADO ) NOT DEFERRABLE ;
