
CREATE TABLE CS_PLAN
  (
    ID_PLAN_CS    NUMBER (5) NOT NULL ,
    DESC_PLAN     VARCHAR2 (30) ,
    SALDO_INICIAL NUMBER (10)
  ) ;
ALTER TABLE CS_PLAN ADD CONSTRAINT CS_PLAN_PK PRIMARY KEY ( ID_PLAN_CS ) ;


CREATE TABLE CS_SALDOS
  (
    ID_SERVICIO        NUMBER (5) NOT NULL ,
    SALDO_INICIAL      NUMBER (10) ,
    SALDO_ACTUAL       NUMBER (10) ,
    FECHA_ULTIMO_SALDO DATE
  ) ;
ALTER TABLE CS_SALDOS ADD CONSTRAINT CS_SALDOS_PK PRIMARY KEY ( ID_SERVICIO ) ;


CREATE TABLE CS_SERVICIO
  (
    ID_SERVICIO        NUMBER (5) NOT NULL ,
    ID_PLAN_CS         NUMBER (5) NOT NULL ,
    ID_SERVICIO_ESTADO VARCHAR2 (1) NOT NULL ,
    MSISDN             VARCHAR2 (10) ,
    FECHA_ACTIVACION   DATE
  ) ;
ALTER TABLE CS_SERVICIO ADD CONSTRAINT CS_SERVICIO_PK PRIMARY KEY ( ID_SERVICIO ) ;


CREATE TABLE CS_SERVICIO_ESTADO
  (
    ID_SERVICIO_ESTADO VARCHAR2 (1) NOT NULL ,
    DESC_ESTADO        VARCHAR2 (30)
  ) ;

ALTER TABLE CS_SERVICIO_ESTADO ADD CONSTRAINT CS_SERVICIO_ESTADO_PK PRIMARY KEY ( ID_SERVICIO_ESTADO ) ;

ALTER TABLE CS_SALDOS ADD CONSTRAINT CS_SALDOS_CS_SERVICIO_FK FOREIGN KEY ( ID_SERVICIO ) REFERENCES CS_SERVICIO ( ID_SERVICIO ) ;

ALTER TABLE CS_SERVICIO ADD CONSTRAINT CS_SERVICIO_CS_PLAN_FK FOREIGN KEY ( ID_PLAN_CS ) REFERENCES CS_PLAN ( ID_PLAN_CS ) ;

ALTER TABLE CS_SERVICIO ADD CONSTRAINT CS_SERVICIO_ESTADO_FK FOREIGN KEY ( ID_SERVICIO_ESTADO ) REFERENCES CS_SERVICIO_ESTADO ( ID_SERVICIO_ESTADO ) ;
